import{a as u,S as p,i as l}from"./assets/vendor-64b55ca9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();async function f(s,e){const a="42307458-71f98d2a331f0bd294b8fc1ec",r="https://pixabay.com"+"/api/",i={key:a,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await u.get(r,{params:i})).data}let c;const o={form:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function d(s){return s.map(e=>`
      <li class="gallery-item"><a href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
            <div class="info">
            <p> <span class="info-text">Likes</span> <br/> ${e.likes}</p>
            <p><span class="info-text">Views</span> <br/> ${e.views}</p>
            <p><span class="info-text">Comments</span> <br/> ${e.comments}</p>
            <p><span class="info-text">Downloads</span> <br/> ${e.downloads}</p>
            </div>
            </li>
      `).join("")}function m(s){const e=d(s);o.gallery.innerHTML=e,typeof c<"u"?c.refresh():c=new p(".gallery a",{captionsData:"alt",captionDelay:250})}o.loader.style.display="none";let y;o.form.addEventListener("submit",g);async function g(s){if(h(),s.preventDefault(),Math.ceil(data.totalResults/15),o.input.value.trim()===""){l.error({message:"Please enter a search query.",position:"topRight",transitionIn:"fadeInLeft"});return}o.gallery.innerHTML="",o.loader.style.display="block";const a=s.target.elements.search.value.trim();try{const n=await f(a,y);n.hits.length===0?(o.loader.style.display="none",l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})):m(n.hits)}catch(n){l.error({message:n.message||"An error occurred. Please try again later.",position:"topRight",transitionIn:"fadeInLeft"})}o.loader.style.display="none",s.target.reset()}function h(){o.gallery.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
